language: java
install: true
addons:
  sonarcloud:
    organization: "gruelbox"
    token:
      secure: "qF7IYWs+PkVwUogHer2btzMAlbQYBJ1rgYd3IyNHBjNFxXI2t1PyV7djOE7E8Nv0rOW/iQZxULQKRrFnebALFIpqWr5VpeuERwTd4sEPZWzjO2irKJvpsd+Rec8i3UOAXuLGe1mtfxj+cggxZDYSgUeQqGntKJAWmffiV6YwEOTEqkvShUN+kt7IW+WW9S4pbIM4znSNLklC5C3Gn25JVuLDIi3K3YL/PtFL0HDREhw2t4FeUb+gmmnjhBxC35Hi+DJTHmyEzuok3V2G0qrgd/9ZvwuP5wQgG1n104UjCZIhb1HfTQ24GGs6+Eb6dDX/AfbBTpsJuHkcGBJGHkP6sfa2dQ4rwE4bs4Ermb7VsKzxspUPw3E3SvSTc78jMW3/Bz0+PxmvPLbQ8SVD2GLR++quoH9qhE6iqxFNPagpprzl4qIl0N/mAPg6qSCwED4OhUXOzR2zdPVnuse4/eC19tyAPGN2VsB74EdgEvgBQrmZRDY6E0CtO6+yqmbEm+OKToCP+rYWRxXvjF5TMLHJIIzVobiO21tzlzvSPleuB1vJsWeKNMd2hmqjaMVZTjxgas35pS4Lx/QCG4TqNZ11awMuyqruAFFCOBXgMDT8GBXZllfae8InUh6kcX6pikSTV5/nBX9d9Oy6D5nm5SmlY0qFsB0AA8o0LZ15dHCszjg="
notifications:
  slack: gruelbox:KxlNRVRsbXFQkO94YtHSdAmS
jobs:
  include:
    - if: repo = gruelbox/kucoin-java-sdk AND branch = master AND NOT type = pull_request
      name: "Test"
      script:
        - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent test sonar:sonar -Pcoverage-per-test -B -U
    - if: repo = gruelbox/kucoin-java-sdk AND NOT branch = master AND NOT type = pull_request
      name: "Test"
      script:
        - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent test sonar:sonar -Pcoverage-per-test -B -U -Dsonar.branch.name=$TRAVIS_BRANCH
    - if: repo = gruelbox/kucoin-java-sdk AND head_repo = gruelbox/kucoin-java-sdk AND type = pull_request
      name: "Test"
      script:
        - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent test sonar:sonar -Pcoverage-per-test -B -U -Dsonar.pullrequest.key=$TRAVIS_PULL_REQUEST -Dsonar.pullrequest.branch=$TRAVIS_PULL_REQUEST_BRANCH -Dsonar.pullrequest.base=$TRAVIS_BRANCH
    - if: repo = gruelbox/kucoin-java-sdk AND (branch = master OR tag IS present) AND NOT type = pull_request
      name: "Deploy"
      script:
        - echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import
        - echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust
        - mvn clean deploy --settings .maven-settings.xml -B -U -Prelease
    - if: (repo = gruelbox/kucoin-java-sdk AND NOT head_repo = gruelbox/kucoin-java-sdk AND type = pull_request) OR NOT repo = gruelbox/kucoin-java-sdk
      name: "Test"
      script:
        - mvn clean test -B -U
matrix:
  fast_finish: true
  include:
    - jdk: oraclejdk8
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'