language: java
install: true
addons:
  sonarcloud:
    organization: "gruelbox"
    token:
      secure: "G0Z5CBaCVENAN91FTPIg0pIcln93JP5e9hho5bs68/+CpXJjamZuy/CSlwdw3njjbZByx4+MbVCtgwYXndoLQM0P1g5LoPW4R0M7QOHBSvmvibzZN2fG4GuXFsOvDSTQbyamPPTv1hSRR+KuhCDD80m1WlWrbzNJknnMADE+cuM1HfZHTa9H9Yz4+N3YhqwKdStnWbBv9PCVDptenXu+iHWJkvI8i9c8lHcIoyJtWkEuAeurzYoocXs4FBS7YOqG6oIOV2S8qd7t74Au1p3dLYVBx8/fyB3H2mZAcsJx0d1OOwwFqTElxuEg16z5AtKKkxLfDDP5MgbkVx54SID33fagU0TMCNXd6BpqaLpnpMRBZ7bBCB08wFNBAGjbfCuMoYJyhqZiosR1YDMbNt1+cXuPiCx/0UtdTf3uAWxTXzKH7/bMEKSVovHHrr45quddT/JYn3JUQ+Zq0VeDloOIR/gHtbua40Nf2sdPWPHzM3DDNtiCDe/uFmdDwcUsNOCLe2PFbiN/PjXCx/H2bz73Cb48r6WWhqkapBpJntnuKS5Yjh2tj7+ry6aUeNrbC/ZJ99z/MFD0kbscD6uOjzaox4ggl3ZvmxuEEgH3vpGZASkKHooqWZTZ8KlwMqetVKtWHc0bsYfgjrDDUjpErFkz8qv2118qlqXrIQixztXQQfw="
notifications:
  slack: gruelbox:KxlNRVRsbXFQkO94YtHSdAmS
jobs:
  include:
    - if: repo = gruelbox/kucoin-java-sdk AND branch = master AND NOT type = pull_request
      name: "Test"
      script:
        - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent test sonar:sonar -Pcoverage-per-test -B -U
    - if: repo = gruelbox/kucoin-java-sdk AND NOT branch = master AND NOT type = pull_request
      name: "Test"
      script:
        - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent test sonar:sonar -Pcoverage-per-test -B -U -Dsonar.branch.name=$TRAVIS_BRANCH
    - if: repo = gruelbox/kucoin-java-sdk AND head_repo = gruelbox/kucoin-java-sdk AND type = pull_request
      name: "Test"
      script:
        - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent test sonar:sonar -Pcoverage-per-test -B -U -Dsonar.pullrequest.key=$TRAVIS_PULL_REQUEST -Dsonar.pullrequest.branch=$TRAVIS_PULL_REQUEST_BRANCH -Dsonar.pullrequest.base=$TRAVIS_BRANCH
    - if: repo = gruelbox/kucoin-java-sdk AND (branch = master OR tag IS present) AND NOT type = pull_request
      name: "Deploy"
      script:
        - echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import
        - echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust
        - mvn clean deploy --settings .maven-settings.xml -B -U -Prelease
    - if: (repo = gruelbox/kucoin-java-sdk AND NOT head_repo = gruelbox/kucoin-java-sdk AND type = pull_request) OR NOT repo = gruelbox/kucoin-java-sdk
      name: "Test"
      script:
        - mvn clean test -B -U
matrix:
  fast_finish: true
  include:
    - jdk: oraclejdk8
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'